group 'com.deeptaai.klaritics.flutter'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://asia-south1-maven.pkg.dev/org-infra-471907/klaritics-android-sdk"
        }
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.hasProperty('android')) {
        if (project.android.hasProperty("namespace")) {
            namespace 'com.deeptaai.klaritics.flutter'
        }
    }
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }
}

dependencies {
    compileOnly "com.deeptaai.klaritics:klaritics-android-sdk:1.0.0"
}
